### ISSUE TITLE
Cannot create a project using you project template

### ISSUE THREAD

**Issue by super2ni** [AJIXuMuK/generator-vuespfx#16]
Hello,

I failed to create a project using your template.
It seems to create the folder but not doing anything.

Here is the repro steps:
![untitled](https://user-images.githubusercontent.com/35492699/44661399-da14ef00-aa0a-11e8-8994-76b2c3f6e8d3.png)

FYI, I use @microsoft/generator-sharepoint 1.4.0.

Thank you,
Denis

**Comment by AJIXuMuK** [comment]
Hello @super2ni ,

Could you please provide more info as I can't reproduce the issue using the same input as you are.
1. Have you installed the vuespfx generator globally (`npm i -g generator-vuespfx`)?
2. What version of the generator do you use?
3. What's your OS?
4. Have you tried to re-install the vuespfx generator after you experienced the error?

Thanks!

**Comment by super2ni** [comment]
I've made a fresh installation of my environnement using Spfx1.6 and now it seems to work.
Sorry for the inconvenience.
